name: "Setup"
description: "Downloads and loads build image"

inputs:
  image_name:
    description: “Build image name”
    required: false
  github_token:
    required: true
  pull_sha:
    required: true

runs:
  using: "composite"
  steps:
    - uses: dawidd6/action-download-artifact@v2.24.2
      with:
        github_token: ${{inputs.github_token}}
        workflow: dependencies_image.yml
        workflow_conclusion: success
        commit: ${{inputs.pull_sha}}
        event: push
        name: otel-cpp-deps
        path: /opt/
        skip_unpack: true
        if_no_artifact_found: warn

    - name: Load deps image
      run: |
        cd /opt
        unzip otel-cpp-deps.zip
        rm -rf otel-cpp-deps.zip
        docker load -i /opt/otel-cpp-deps-debian.tar
