exporters:
  logging:
    loglevel: DEBUG
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls_settings:
          cert_file: /opt/server.crt
          key_file: /opt/server.pem
      http:
        endpoint: 0.0.0.0:4318
        cors_allowed_origins:
        - '*'
service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - logging
    logs:
      receivers:
      - otlp
      exporters:
      - logging
