name: OpenTelemetry-cpp benchmarks
on:
  push:
    branches:
      - benchmark-action

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run OpenTelemetry-cpp benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        components: ["api", "sdk", "exporters"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Mount Bazel Cache
        uses: actions/cache@v2
        env:
          cache-name: bazel_cache
        with:
          path: /home/runner/.cache/bazel
          key: bazel_benchmark
      - name: setup
        run: |
          sudo ./ci/setup_cmake.sh
          sudo ./ci/setup_ci_environment.sh
      - name: Run benchmark
        id: run_benchmarks
        run: |
          env BENCHMARK_DIR=/benchmark
          ci/do_ci.sh bazel.benchmark
          #echo "::set-output name=json_plaintext::$(cat benchmark_result.json)"
      - name: Store benchmark result
        #if: steps.run_benchmarks.outputs.json_plaintext != 'null'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: OpenTelemetry-cpp ${{ matrix.components }} Benchmark
          tool: 'googlecpp'
          output-file-path: ${{ matrix.components }}-benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@esigo'
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
