name: OpenTelemetry-cpp benchmarks
on:
  push:
    branches:
      - benchmark-action

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run OpenTelemetry-cpp benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: setup
        run: |
          sudo ./ci/setup_cmake.sh
          sudo ./ci/setup_ci_environment.sh
          sudo ./ci/setup_thrift.sh dependencies_only
      - name: Run benchmark
        run: |
          ci/do_ci.sh bazel.benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: OpenTelemetry-cpp Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@esigo'
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
