name: OpenTelemetry-cpp benchmarks
on:
  schedule:
    - cron: 30 * * * *

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: OpenTelemetry-cpp Mac benchmarks
    runs-on: macos-latest
    outputs:
      output1: ${{ steps.run_benchmarks.outputs.test }}
      api_result: ${{ steps.run_benchmarks.outputs.api_json }}
      sdk_result: ${{ steps.run_benchmarks.outputs.sdk_json }}
      exporters_result: ${{ steps.run_benchmarks.outputs.exporters_json }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Mount Bazel Cache
        uses: actions/cache@v2
        env:
          cache-name: bazel_cache
        with:
          path: /Users/runner/.cache/bazel
          key: bazel_osx
      - uses: docker-practice/actions-setup-docker@1.0.8
      - name: Run benchmark
        id: run_benchmarks
        run: |
          ci/do_ci.sh bazel.benchmark
          mkdir -p benchmarks
          mv api-benchmark_result.json benchmarks
          mv sdk-benchmark_result.json benchmarks
          mv exporters-benchmark_result.json benchmarks
      - uses: actions/upload-artifact@master
        with:
          name: benchmark_results
          path: benchmarks
  store_benchmark:
    needs: benchmark
    strategy:
      matrix:
        components: ["api", "sdk", "exporters"]
    name: Store benchmark result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: benchmark_results
          path: benchmarks
      - name: Store json files
        id: store_json
        run: |
          cat benchmarks/*
          echo ${{needs.benchmark.outputs.api_result}} | tee api-benchmark_result.json
          echo ${{needs.benchmark.outputs.sdk_result}} | tee sdk-benchmark_result.json
          echo ${{needs.benchmark.outputs.exporters_result}} | tee exporters-benchmark_result.json
      - name: Print json files
        id: print_json
        run: |
          cat benchmarks/*
      - name: Push benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: OpenTelemetry-cpp ${{ matrix.components }} Benchmark
          tool: 'googlecpp'
          output-file-path: benchmarks/${{ matrix.components }}-benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
