name: 'Build Multi-Platform OpenTelemetry Docker image'
on:
  push:
    branches:
      - artifacts
# on:
#   schedule:
#     - cron: '30 1 * * *'

jobs:
  docker_image:
    name: Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    -
      name: checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build Image
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ci/
        file: ./docker/ubuntuLatest/Dockerfile
        build-args: BASE_IMAGE=ubuntu:latest
        platforms: linux/amd64
        # platforms: linux/amd64,linux/arm64
        push: false
        tags: otel-cpp
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Save Image
      run: |
        docker save -o /opt/otel-cpp.tar otel-cpp
    -
      name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: otel-cpp-deps
        path: /opt/otel-cpp-deps.tar