name: 'OpenTelemetry-cpp dependencies image'
on:
  schedule:
    - cron: "0 3 * * 6"
  push:
    branches: [ main, docker ]
  pull_request:
    branches: [ main ]

jobs:
  docker_image:
    name: Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    -
      name: checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build gRPC Image
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: docker/grpc
        file: ./docker/grpc/Dockerfile
        build-args: |
          "BASE_IMAGE=ubuntu:latest"
          "GRPC_GIT_TAG=v1.48.1"
          "CORES=3"
        platforms: linux/amd64
        # platforms: linux/amd64,linux/arm64
        push: false
        tags: otel-cpp-grpc
        load: true
    -
      name: Save Image
      run: |
        docker images
        docker save -o /opt/otel-cpp-grpc-debian.tar otel-cpp-grpc
    -
      name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: otel-cpp-grpc
        path: /opt/otel-cpp-grpc-debian.tar
        retention-days: 14
