name: OpenTelemetry-cpp dependencies download

on:
  push:
    branches:
      - bzl

jobs:
  cmake_otlp:
    name: CMake test (with otlp-exporter)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: ./.github/actions/setup
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        pull_sha: ${{github.event.pull_request.head.sha}}
    - name: cmake test
      run: |
        docker images
        bash ci/ci_run_docker.sh ci/do_ci.sh cmake.exporter.otprotocol.test
