name: OpenTelemetry-cpp dependencies download
on:
  push:
    branches:
      - bzl
jobs:
  download_artifact:
    name: download artifact
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2.24.2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          #run_id: 3609494423
          # https://github.com/dawidd6/action-download-artifact/issues/147
          workflow: dependencies_image.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          branch: bzl
          event: push
          name: otel-cpp-deps
          path: /opt/
          skip_unpack: true
      - name: Load deps image
        run: |
          cd /opt
          unzip otel-cpp-deps.zip
          rm -rf otel-cpp-deps.zip
          docker load -i /opt/otel-cpp-deps-debian.tar
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: cmake test
        run: |
          docker images
          bash ci/ci_run_docker.sh ci/do_ci.sh cmake.exporter.otprotocol.test
