name: OpenTelemetry-cpp dependencies download
on:
  push:
    branches:
      - artifacts
- name: Download artifact
  uses: dawidd6/action-download-artifact@v2
  with:
    workflow: dependencies.yml
    workflow_conclusion: success
    branch: artifacts
    event: push
    name: my-artifact
    path: /
    run: |
      cat /*.txt